import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { TaskProvider } from "../context/TaskContext";
import Link from "next/link";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className="flex h-screen bg-gray-50 text-gray-900 font-sans">
        <TaskProvider>
          <aside className="w-64 bg-gray-900 text-white p-4 space-y-4">
            <h2 className="text-xl font-bold">Kappa Tracker</h2>
            <nav className="flex flex-col space-y-2">
              <Link href="/" className="hover:underline">Active Tasks</Link>
              <Link href="/completed" className="hover:underline">Completed Tasks</Link>
            </nav>
          </aside>
          <main className="flex-1 bg-gray overflow-y-auto">
            {children}
          </main>
        </TaskProvider>
      </body>
    </html>
  );
}
